#!/usr/bin/env python
from app.pacman import update
from app import db
from app.model import CVEGroup
from app.model.enum import Status, Affected
from app.util import affected_to_status


def update_group_status():
    groups = (db.session.query(CVEGroup).filter(CVEGroup.status.in_([Status.vulnerable, Status.testing]))).all()
    for group in groups:
        group.status = affected_to_status(Affected.affected, group.pkgname, group.fixed)
    db.session.commit()


update()
update_group_status()
